version: 0.2

phases:
  install:
    commands:
      - echo Installing AWS CLI
      - pip install awscli
  build:
    commands:
      - echo Deploying CloudFormation stack
      - aws cloudformation deploy --template-file ec2-instance.yaml --stack-name my-ec2-stack-${CODEBUILD_BUILD_ID}

artifacts:
  files:
    - '**/*'
