version: 0.2

phases:
  install:
    commands:
      - echo "Installing AWS CLI"
      - pip install awscli

  build:
    commands:
      - echo "Running deployment script"
      - ./deploy.sh

artifacts:
  files:
    - '**/*'
