version: 0.2

phases:
  build:
    commands:
      - echo Deploying CloudFormation stack
      - aws cloudformation deploy --template-file ec2-instance.yaml --stack-name my-ec2-stack-${CODEBUILD_BUILD_NUMBER}

artifacts:
  files:
    - '**/*'
