AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-066784287e358dad1
      Tags:
        - Key: Name
          Value: MyEC2Instance
