AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceName:
    Type: String
    Description: The name of the EC2 instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-066784287e358dad1
      Tags:
        - Key: Name
          Value: !Ref InstanceName
